### ISSUE TITLE
Confusingly takes directories as INPUT, not files

### ISSUE THREAD

**Issue by mikegerber** [cneud/alto-tools#2]
The script confusingly takes only directories as INPUT, not files.

works:
python3 alto_tools.py ~/devel/experiments/tesseract-fraktur/ --text

does NOT work:
python3 alto_tools.py ~/devel/experiments/tesseract-fraktur/test-frak.xml --text

**Comment by cneud** [comment]
Yes, the whole i/o needs fixing or even better, a replacement with ``click``. I had to abandon work on this due to other urgent business and never got round to fixing this. PR welcome ;-)

**Comment by mikegerber** [comment]
AFAICS, intended behaviour should be:

* If an INPUT element is a file, read it
* If an INPUT element is a directory, read all XML files in it, recursively

Is that correct?

**Comment by cneud** [comment]
@mikegerber Yes, that would have been the intention.
